### ISSUE TITLE
Credit spreads

### ISSUE THREAD

**Issue by pdavidsonFIA** [DeNederlandscheBank/solvency2-data-science#3]
A useful feature would be to include the credit spreads to derive a risky rate at the same time as the risk free rate. The data is in the CoD file.

**Comment by wjwillemse** [comment]
I assume that this issue relates to the solvency2-data package. Could you please specify which credit spreads you need (with possibly reference to the Excel sheet). The CoD Excel file contains several sets of credit spreads.

**Comment by pdavidsonFIA** [comment]
HI, yes the solvency2 data.
For example the fundamental credit spread for financial corporates, EUR.

**Comment by wjwillemse** [comment]
Financial fundamental spreads, non-financial fundamental spreads and central government fundamental spreads for all languages have been added to the general dictionary in solvency2-data package, version 0.1.5. You have to upgrade the package to install the latest version. Hope it works.

**Comment by pdavidsonFIA** [comment]
This works great (especially with the EIOPA link correction).
Thank you very much!
